name: Clientes DB Sync
slug: clientes_db
version: "1.0.0"
description: Sincronizaci√≥n de base de clientes
startup: services
boot: auto

arch:
  - amd64
  - aarch64
  - armv7

ports:
  3000/tcp: 3000

image: null
